(defun n-queens (n)
  (defun place (i sol cols diags cdiags)
    (if (= i n)
        (print sol)
        (dotimes (j n)
          (when (and (zerop (logand (ash 1 j) cols))
                     (zerop (logand (ash 1 (+ i j)) diags))
                     (zerop (logand (ash 1 (+ i (- n 1 j))) cdiags)))
            (place (+ 1 i)
                   (+ (list j) sol)
                   (logior (ash 1 j) cols)
                   (logior (ash 1 (+ i j)) diags)
                   (logior (ash 1 (+ i (- n 1 j))) cdiags))))))
  (place 0 (list) 0 0 0))

(n-queens 8)
